In [1]:
d={}

In [2]:
type(d)

dict

In [5]:
d1={"Name":"Zubair","Father_Name":"Fayaz_Ah","D.O.B":1997,
"Salary":80000,"Dept":"CSE"}

In [6]:
d1

{'Name': 'Zubair',
 'Father_Name': 'Fayaz_Ah',
 'D.O.B': 1997,
 'Salary': 80000,
 'Dept': 'CSE'}

In [9]:
d1['Name']="kubair"
print(d1)

{'Name': 'kubair', 'Father_Name': 'Fayaz_Ah', 'D.O.B': 1997, 'Salary': 80000, 'Dept': 'CSE'}

In [11]:
d2={'Name': 'Zubair',
 'Father_Name': 'Fayaz_Ah',
 'D.O.B': 1997,
 'Salary': 80000,
 'Dept': 'CSE',"Name":"ABC"}

In [12]:
d2

{'Name': 'ABC',
 'Father_Name': 'Fayaz_Ah',
 'D.O.B': 1997,
 'Salary': 80000,
 'Dept': 'CSE'}

In [15]:
d3={1:"yash"}

In [17]:
d3={(1,2,3):"yash"}

In [18]:
d3

{(1, 2, 3): 'yash'}

In [19]:
d={'Name': 'ABC',
 'Father_Name': 'Fayaz_Ah',
 'D.O.B': 1997,
 'Salary': 80000,
 'Dept': 'CSE'}

In [20]:
d

{'Name': 'ABC',
 'Father_Name': 'Fayaz_Ah',
 'D.O.B': 1997,
 'Salary': 80000,
 'Dept': 'CSE'}

In [21]:
d.get('Salary')

80000

In [22]:
d['Salary']

80000

In [23]:
d.items()

dict_items([('Name', 'ABC'), ('Father_Name', 'Fayaz_Ah'), ('D.O.B', 1997), ('Salary', 80000), ('Dept', 'CSE')])

In [24]:
d.keys()

dict_keys(['Name', 'Father_Name', 'D.O.B', 'Salary', 'Dept'])

In [25]:
d.values()

dict_values(['ABC', 'Fayaz_Ah', 1997, 80000, 'CSE'])

In [28]:
s=("yash","dipreet")
s1=1
dict.fromkeys(s,s1)

{'yash': 1, 'dipreet': 1}

In [32]:
d.pop('Name')

'ABC'

In [33]:
d

{'Father_Name': 'Fayaz_Ah', 'D.O.B': 1997, 'Salary': 80000, 'Dept': 'CSE'}

In [34]:
d.popitem()

('Dept', 'CSE')

In [35]:
d

{'Father_Name': 'Fayaz_Ah', 'D.O.B': 1997, 'Salary': 80000}

In [37]:
d.setdefault('D.O.B',2000)

1997

In [40]:
d.update({'D.O.B':2000})

In [41]:
d

{'Father_Name': 'Fayaz_Ah', 'D.O.B': 2000, 'Salary': 80000}

In [42]:
d.setdefault("Name","Yash")

'Yash'

In [43]:
d.update({"Role":"Teacher"})

In [44]:
d

{'Father_Name': 'Fayaz_Ah',
 'D.O.B': 2000,
 'Salary': 80000,
 'Name': 'Yash',
 'Role': 'Teacher'}

In [47]:
d={'Fruits':["Banana","Orange","Apple","Grapes"],
   'Size':[20,30,40,60],
   'Weight':[80,20,40,25],
   'Color':['Yellow','Orange','Red','Green']}

In [48]:
d

{'Fruits': ['Banana', 'Orange', 'Apple', 'Grapes'],
 'Size': [20, 30, 40, 60],
 'Weight': [80, 20, 40, 25],
 'Color': ['Yellow', 'Orange', 'Red', 'Green']}

In [53]:
import pandas as pd
df=pd.DataFrame(d)

In [54]:
df

   Fruits  Size  Weight   Color
0  Banana    20      80  Yellow
1  Orange    30      20  Orange
2   Apple    40      40     Red
3  Grapes    60      25   Green

In [55]:
df.describe()

            Size     Weight
count   4.000000   4.000000
mean   37.500000  41.250000
std    17.078251  27.195281
min    20.000000  20.000000
25%    27.500000  23.750000
50%    35.000000  32.500000
75%    45.000000  50.000000
max    60.000000  80.000000

In [58]:
x=10
if x==10:
    print("x is equal to 10")

x is equal to 10

In [60]:
x=10
if x>10:
    print("x is equal to 10")
else:
    print("x is not greater than 10")

x is not greater than 10

In [66]:
age=18
if age>=18:
    print("person is eligible for vote")
else:
    print("person is not eligible for vote")

person is eligible for vote

In [65]:
age=18
if age>18:
    print("person is eligible for vote")
else:
    print("person is not eligible for vote")

person is not eligible for vote

In [1]:
age=int(input("Enter the Age:="))
if age>=18:
    print("person is eligible for vote")
else:
    print("print is not eligible for vote")

Enter the Age:=18
person is eligible for vote

In [69]:
x=int(input("Enter the first number:="))
y=int(input("Enter the second number:="))
z=int(input("Enter the third number:="))
if x>y and x>z:
    print("X is greatest among all")
elif y>z:
     print("Y is greatest among all")
else:
     print("Z is greatest among all")

Enter the first number:=12
Enter the second number:=40
Enter the third number:=60
Z is greatest among all

In [4]:
a=int(input("Enter the first number:="))
b=int(input("Enter the second number:="))
c=int(input("Enter the third number:="))
d=int(input("Enter the fourth number:="))
e=int(input("Enter the fifth number:="))
if a>b and a>c and a>d and a>e:
    print("a is greatest among all")
elif b>c and b>d and b>e:
    print("b is greatest among all")
elif c>d and c>e:
    print("c is greatest among all")
else d>e:
    print("e is greatest among all")

SyntaxError: expected ':' (511447061.py, line 12)

In [5]:
x=100 
if x>10:
    print("x is satisfied")
    if x>=50:
        print("abrdwsr")
    else:
        print("jiryhthhfrd")

x is satisfied
abrdwsr

In [6]:
a=int(input("Enter the first number:="))
b=int(input("Enter the second number:="))
c=int(input("Enter the third number:="))
d=int(input("Enter the fourth number:="))
e=int(input("Enter the fifth number:="))
if a>b and a>c and a>d and a>e:
    print("A is greatest among all")
elif b>c and b>d and b>e:
    print("B is greatest among all")
elif c>d and c>e:
    print("C is greatest among all")
elif d>e:
    print("D is greatest among all")
else:
    print("E is greatest among all")

Enter the first number:=12
Enter the second number:=30
Enter the third number:=40
Enter the fourth number:=48
Enter the fifth number:=20
D is greatest among all

In [3]:
x=100 
if x>10:
    print("x is satisfied")
    if x>=50:
        print("abrdwsr")
    else:
        print("jiryhthhfrd")

x is satisfied
abrdwsr